name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            pack ./eventhub
        env: 
          JAVA_HOME: /usr/lib/jvm/default-jvm
      - name: Ballerina Tests
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            test ./eventhub
        env: 
          JAVA_HOME: /usr/lib/jvm/default-jvm
          SAS_KEY_NAME: ${{ secrets.SAS_KEY_NAME }}
          SAS_KEY: ${{ secrets.SAS_KEY }}
          RESOURCE_URI: ${{ secrets.RESOURCE_URI }}
